#!/usr/bin/env node
/**
 * Auto-creates .env.local with a random BETTER_AUTH_SECRET if it doesn't exist.
 * Runs automatically before `npm run dev` and `npm run build`.
 */
const fs = require("fs");
const path = require("path");
const crypto = require("crypto");

const envPath = path.join(__dirname, "..", ".env.local");

if (fs.existsSync(envPath)) {
  process.exit(0);
}

const secret = crypto.randomBytes(32).toString("base64");

const content = `# Auto-generated by scripts/ensure-env.js
# Edit as needed for your environment.

BETTER_AUTH_SECRET=${secret}
BETTER_AUTH_URL=http://localhost:3000
NEXT_PUBLIC_API_URL=http://127.0.0.1:8001
`;

fs.writeFileSync(envPath, content, "utf-8");
console.log("Created frontend/.env.local with auto-generated secret.");
console.log("Edit it if you need a different API URL or port.\n");
